"""Generate KSPChatMod/NativeToolSchemas.cs: OpenAI tool schemas for every NativeCommands.Ported tool, from the
bridge's python signatures/docstrings (kspchat.ksp_actions.BY_NAME). Run: python tools/gen_tool_schemas.py"""
import inspect, json, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
OUT = os.path.join(ROOT, "KSPChatMod", "NativeToolSchemas.cs")
TYPES = {float: "number", int: "integer", bool: "boolean", str: "string"}


def ported():
    src = open(os.path.join(ROOT, "KSPChatMod", "NativeCommands.cs"), encoding="utf-8").read()
    block = src[src.index("Ported = new"):]
    block = block[block.index("{"):block.index("};")]
    block = re.sub(r"//[^\n]*", "", block)
    return [n for n in re.findall(r'"([^"]+)"', block) if "/" not in n]


def short(doc, limit=160):
    d = " ".join((doc or "").split())
    m = re.match(r"(.+?[.!?])(\s|$)", d)
    d = m.group(1) if m else d
    return d if len(d) <= limit else d[:limit - 3].rstrip() + "..."


def schemas():
    from kspchat import ksp_actions as k
    out, missing = [], []
    for name in ported():
        fn = k.BY_NAME.get(name)
        if fn is None:
            missing.append(name)
            continue
        props, req = {}, []
        for p in inspect.signature(fn).parameters.values():
            if p.kind in (p.VAR_POSITIONAL, p.VAR_KEYWORD):
                continue
            props[p.name] = {"type": TYPES.get(p.annotation, "string")}
            if p.default is inspect.Parameter.empty:
                req.append(p.name)
        params = {"type": "object", "properties": props}
        if req:
            params["required"] = req
        out.append({"type": "function", "function": {"name": name, "description": short(fn.__doc__), "parameters": params}})
    return out, missing


def render():
    tools, missing = schemas()
    js = json.dumps(tools, separators=(",", ":"), ensure_ascii=True)
    return ("// GENERATED by tools/gen_tool_schemas.py from kspchat.ksp_actions - do not edit by hand.\n"
            "namespace KSPChatBridge\n{\n    internal static class NativeToolSchemas\n    {\n"
            "        internal const int Count = %d;\n"
            "        // ported but not a bridge tool (no schema): %s\n"
            "        internal const string Json = @\"%s\";\n    }\n}\n") % (len(tools), ", ".join(missing) or "none", js.replace('"', '""'))


if __name__ == "__main__":
    open(OUT, "w", encoding="utf-8", newline="\n").write(render())
    print(OUT)
