"""Generate KSPChatMod/PersonalityPrompts.cs from personalities.txt (Luke's short 3B role-play prompts).
Run: python tools/gen_personalities.py"""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "personalities.txt")
OUT = os.path.join(ROOT, "KSPChatMod", "PersonalityPrompts.cs")
ROLE = {"pilot": r"\b(pilot|copilot|commander|navigator|veteran|cadet|rookie|racer|daredevil)\b",
        "scientist": r"\b(scientist|geologist|meteorologist|explorer)\b",
        "engineer": r"\b(engineer|mechanic|tinkerer|technician|inspector)\b",
        "tourist": r"\b(tourist|actor|musician|cook|gambler|parent|intern)\b"}


def parse():
    out = []
    for line in open(SRC, encoding="utf-8", errors="replace"):
        m = re.match(r"\s*\d+\.\s*(.+?)\s+\S\s+.*?PROMPT:\s*\"(.+)\"\s*$", line)
        if not m:
            continue
        title, prompt = m.group(1).strip(), m.group(2).strip()
        low = (title + " " + prompt).lower()
        role = next((r for r, rx in ROLE.items() if re.search(rx, low)), "any")
        out.append((title, role, prompt))
    return out


def render():
    rows = parse()
    def s(x):
        return json.dumps(x, ensure_ascii=True)
    body = ",\n".join(f"            new[] {{ {s(t)}, {s(r)}, {s(p)} }}" for t, r, p in rows)
    return ("// GENERATED by tools/gen_personalities.py from personalities.txt - do not edit by hand.\n"
            "namespace KSPChatBridge\n{\n    internal static class PersonalityPrompts\n    {\n"
            "        /// <summary>{title, role (pilot|scientist|engineer|tourist|any), short role-play prompt}.</summary>\n"
            "        internal static readonly string[][] All =\n        {\n" + body + "\n        };\n    }\n}\n")


if __name__ == "__main__":
    open(OUT, "w", encoding="utf-8", newline="\n").write(render())
    print(OUT, len(parse()))
